apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
  namespace: microservices
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi