apiVersion: apps/v1
kind: Deployment
metadata:
  name: settings-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: settings-service
  template:
    metadata:
      labels:
        app: settings-service
    spec:
      containers:
        - name: settings-service
          image: sahilrajputwins/full-stack-app-demo-settings-service
          ports:
            - containerPort: 3003
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "microservices_db"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: JWT_SECRET
              value: "dev-secret-change-me"
